### ISSUE TITLE
Bug when giving a Zenodo url

### ISSUE THREAD

**Issue by bebatut** [bebatut/ptdk#14]

**Comment by agdiaz** [comment]
Hi there 👋 

I received the same "500: internal server error" when using the Zenoro URL through the webserver. I could not be able to extract further details related to the issue unfortunately. I have tried using either the full link "https://zenodo.org/record/XXXXX" or just the ID part of the URL "XXXXX", resulting on the same issue. 

However, and maybe as a workaround, the command-line tool worked fine in my case and I managed to create the tutorial skeleton.

If you are blocked, you may follow the steps defined inside the title " Hands-on: Create the skeleton of a tutorial via the command line" on https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial/tutorial.html. 

Best regards from Brussels,

**Comment by hexylena** [comment]
I'm seeing

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/ptdk/training.py", line 143, in index
    zip_fn = generate(tuto_metadata)
  File "/app/ptdk/training.py", line 83, in generate
    train.init_training(ctx)
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/__init__.py", line 39, in init_training
    self.tuto.create_tutorial(ctx)
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/tutorial.py", line 533, in create_tutorial
    self.prepare_data_library_from_zenodo()
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/tutorial.py", line 463, in prepare_data_library_from_zeno
    files, z_record = self.get_files_from_zenodo()
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/tutorial.py", line 450, in get_files_from_zenodo
    file_dict["ext"] = get_galaxy_datatype(f["type"], self.datatype_fp)
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/tutorial.py", line 556, in get_galaxy_datatype
    datatypes = load_yaml(datatype_fp)
  File "/app/.heroku/python/lib/python3.10/site-packages/planemo/training/utils.py", line 48, in load_yaml
    with open(filepath) as m_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

in the logs currently. That should be fixable.
